### ISSUE TITLE
NuGetPack task doesn't support package metadata

### ISSUE THREAD

**Issue by splatteredbits** [webmd-health-services/Whiskey#153]
Update the `NuGetPack` task to support package metadata. Add a "Metadata" property that is itself a set of key/value pairs. Each key should become an element under the `/package/metadata` element in the .nuspec file. (If `Path` doesn't point to a `.nuspec` file, then ignore Metadata with a warning.)

```
Build:
- NuGetPack:
    Path: LibGit2.PowerShell.nuspec
    Metadata:
        id: LibGit2.PowerShell
        version: $(WHISKEY_SEMVER1)
        releaseNotes: $(WHISKEY_RELEASE_NOTES)
```
