### ISSUE TITLE
Create Credentials task for setting build credentials

### ISSUE THREAD

**Issue by splatteredbits** [webmd-health-services/Whiskey#154]
Create a `Credentials` task that reads credentials from environment variables and encrypted strings. 

```
Build:
- Credentials:
    # This password is stored as a raw string as an environment variable.
    - ID: bitbucketserver.example.com
      UserName: build_user
      EnvironmentVariable: BUILD_USER_PASSWORD

    # This password is stored encrypted as an environment variable. The thumbprint is the private key to use to decrypt the value.
    - ID: npm.example.com
      UserName: build_user
      EnvironmentVariable: BUILD_USER_PASSWORD
      Thumbprint: 843024839028034892034802934

    # This password is stored encrypted in the whiskey.yml file . The thumbprint is the private key to use to decrypt the value.
    - ID: proget.example.com
      UserName: build_user
      EncryptedPassword: "AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAAA+1DCKO6m0203oYfjuDc/AAAAAACAAAAAAADZgAAwAAAABAAAAC8x/beP98ntwJ6DWk11vmjAAAAAASAAACgAAAAEAAAAJoaL21OfwKb6d4jAoxlS4YIAAAAqkfFjeeEp6cUAAAAogc+Cte0E9aol9SSFhYuUU+ycYw="
      Thumbprint: 843024839028034892034802934
```
