### ISSUE TITLE
Create Copy task to copy files and directories

### ISSUE THREAD

**Issue by splatteredbits** [webmd-health-services/Whiskey#274]
Create a `Copy` task that copies files *and* directories. Remove the `CopyFile` task and add a `CopyFile` alias to the new task.

```
- Copy:
    Path:
    - Fubar
    - Snafu
    DestinationPath: SomePath
```
