### ISSUE TITLE
Add a shorthand syntax for the `Npm` task

### ISSUE THREAD

**Issue by DecoyJoe** [webmd-health-services/Whiskey#316]
It would be nice for the `Npm` task to support a shorthand syntax to make multiple `Npm` tasks in a `whiskey.yml` more concise.

From:
```
- Npm:
    Command: install

- Npm:
    Command: audit

- Npm:
    Command: run
    Argument: build
```
To:
```
- Npm: install

- Npm: audit

- Npm: run build
```
