### ISSUE TITLE
Convert Publish-WhiskeyTag to a task

### ISSUE THREAD

**Issue by splatteredbits** [webmd-health-services/Whiskey#4]
Convert the `Publish-WhiskeyTag` function to be a `Publish-WhiskeyBBServerTag` task.

```
BuildTasks:
- PublishBBServerTag:
    BBServerUri: "https://bbserver.example.com/'
    CredentialID: BBServer
```
