### ISSUE TITLE
Pester task validate that Configuration property is missing

### ISSUE THREAD

**Issue by splatteredbits** [webmd-health-services/Whiskey#416]
Run this:

```yaml
- Pester:
    Run:
        Path:
        - Tests\*.Tests.ps1
        Exit: true
    TestResult:
        Enabled: true
        OutputPath: .\.output\pester5.xml
        TestSuiteName: WhsRivetExtensions
    Output:
        Verbosity: Detailed
```

and you'll get a very unhelpful error message because everything should be under a `Configuration` property, like this:

```yaml
- Pester:
    Configuration:
        Run:
            Path:
            - Tests\*.Tests.ps1
            Exit: true
        TestResult:
            Enabled: true
            OutputPath: .\.output\pester5.xml
            TestSuiteName: WhsRivetExtensions
        Output:
            Verbosity: Detailed
```

Print out a better error message.```
