### ISSUE TITLE
Create Env task

### ISSUE THREAD

**Issue by splatteredbits** [webmd-health-services/Whiskey#429]
Create an `Env` task.

```yaml
- Env:
    SomeVar: SomeValue
    Path:
        Prepend: VALUE
        Append: VALUE
        Remove: VALUE
        Separator: VALUE
```
