### ISSUE TITLE
Update ProGetUniversalPackage and Zip tasks to use opt-in whitelists

### ISSUE THREAD

**Issue by splatteredbits** [webmd-health-services/Whiskey#433]
Update the `ProGetUniversalPackage` and `Zip` tasks to use opt-in whitelists. Each should have a mandatory `Path` property which is the list of paths to include in the package. There can be optional `Include` and `Exclude` properties, which are glob patterns that match files under each `Path`. Use the `Glob` module to do the glob searches.

Each `Path` item can be a string (the path to include), or a map whose value is the source path in the package and has these properties: `destination_path`, `include`, `exclude`, `inherit_whitelist`, and `inherit_blacklist`. By default, the top-level `include` and `exclude` properties are inherited.

```yaml
- whiskey.proget_universal_package:
    path:
    - path1 # All files under path1 are added because there is no `include` or `exclude` properties on this task.
    - path2: path2_destination  # All files under path2 are added to the package, but under a `path2_destination` directory.
    # alternative syntax for the above.
    # - path2:
    #    destination_path: path2_destination
    - path3: # include all *.txt files under `path3` except for any `ignore.txt` files.
    - 
        include: [ "**/*.txt" ]
        exclude: [ "**/ignore.txt" ]
```

```yaml
- whiskey.proget_universal_package:
    # By default, only include .html and .js files in the package, Don't include any directories named `internal`.
    include: [ "**/*.html", "**/*.js" ]
    exclude: [ "**/internal/**" ]
    path:
    - .
        exclude: [ "path2/**", "path3/**" ]
    - path2:
        # This path gets filtered differently, so turn off the global rules and only include *.js files except for protected.js files.
        inherit_include: false
        inherit_exclude: false
        include: [ "**/*.js" ]
        exclude: [ "**/protected.js" ]
  - path3:
      # path 3 should *also* include *.css files
      include: [ "*.css" ]
```
