### ISSUE TITLE
Convert New-WhiskeyBuildMasterPackage to a build task

### ISSUE THREAD

**Issue by splatteredbits** [webmd-health-services/Whiskey#6]
Convert the `New-WhiskeyBuildMasterPackage` function into a `PublishBuildMasterPackage` task.

```
PublishTasks:
- PublishBuildMasterPackage:
    BuildMasterUri: https://buildmaster.example.com/
    CredentialID: BuildMaster
    ApiKeyCredentialID: BuildMasterApiKey
    ReleaseName: release
    Applicationname: application_name
    PackageVariables:
        One: Two
        Three: Four
````
