### ISSUE TITLE
Add feed properties to PublishNodeJsModule task

### ISSUE THREAD

**Issue by splatteredbits** [webmd-health-services/Whiskey#8]
Add `RegistryUri`, `CredentialID`, and `Email` properties to the `PublishNodeJsModule` task to replace these properties on the `ProGetSession` property of the task context.

```
PublishTasks:
- PublishNodeJsModule:
    RegistryUri: https://npm.example.com/
    CredentialID: NpmCredential
    Email: user@example.com
```
